# Start with your base image
FROM python:3.9-buster

# Set the working directory in the container
WORKDIR /app

# Copy requirements.txt and then the Flask app
COPY ./requirements.txt /app/requirements.txt
COPY ./back-end /app/

# Install the Python dependencies
RUN pip install --no-cache-dir --upgrade pip && pip install --no-cache-dir -r /app/requirements.txt

ENV FLASK_APP=app.py
CMD ["flask", "run", "--host=0.0.0.0"]
